[project]
name = "contrailopt"
authors = [{ name = "Contrails.org", email = "py@contrails.org" }]
dynamic = ["version"]
description = "Contrail-aware flight optimization"
license = "Apache-2.0"
license-files = ["LICENSE"]
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "pandas",
    "platformdirs",
    "pycontrails",
    "requests",
    "scipy",
    "spherely",
]

[project.optional-dependencies]
vis = [
    "cartopy",
    "matplotlib",
]

[dependency-groups]
dev = [
    "pyarrow",  # test_waypoints writes to parquet
    "pyproj",  # test_slerp
    "pytest",
    "ruff",
]

[build-system]
requires = ["setuptools>=77", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["contrailopt"]

[tool.setuptools_scm]
write_to = "contrailopt/_version.py"
local_scheme = "no-local-version"

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = ["error::UserWarning"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = [
    "B",
    "C4",
    "D",
    "E",
    "F",
    "I",
    "ICN",
    "ISC",
    "NPY",
    "PT",
    "PTH",
    "RET",
    "RUF",
    "S",
    "SIM",
    "TC",
    "TID",
    "UP",
    "W",
]
ignore = [
    "D105",  # Missing docstring in magic method
    "D413",  # Missing blank line after last section
]

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["D", "S101"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"
