name: Tests

on:
  push:
    branches: [main]

  pull_request:

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: '3.14'
      - run: uv run --group dev ruff check
      - run: uv run --group dev pytest
